/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yahoo_jmh_jmhtest_jni_AllocationJNI */

#ifndef _Included_com_yahoo_jmh_jmhtest_jni_AllocationJNI
#define _Included_com_yahoo_jmh_jmhtest_jni_AllocationJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yahoo_jmh_jmhtest_jni_AllocationJNI
 * Method:    allocate
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_yahoo_jmh_jmhtest_jni_AllocationJNI_allocate
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_yahoo_jmh_jmhtest_jni_AllocationJNI
 * Method:    release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_jmh_jmhtest_jni_AllocationJNI_release
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_yahoo_jmh_jmhtest_jni_AllocationJNI
 * Method:    doSomething
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_yahoo_jmh_jmhtest_jni_AllocationJNI_doSomething
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
