/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yahoo_jmh_jmhtest_jni_LotsOfLongs */

#ifndef _Included_com_yahoo_jmh_jmhtest_jni_LotsOfLongs
#define _Included_com_yahoo_jmh_jmhtest_jni_LotsOfLongs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yahoo_jmh_jmhtest_jni_LotsOfLongs
 * Method:    testLongArray
 * Signature: ([J)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_jmh_jmhtest_jni_LotsOfLongs_testLongArray
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     com_yahoo_jmh_jmhtest_jni_LotsOfLongs
 * Method:    testLongParams
 * Signature: (JJJJJJJJ)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_jmh_jmhtest_jni_LotsOfLongs_testLongParams
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
